# Generated by Django 5.2 on 2025-04-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookin_date',
            new_name='booking_date',
        ),
    ]
